# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kali/Desktop/oracel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kali/Desktop/oracel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kali/Desktop/oracel/CMakeFiles /home/kali/Desktop/oracel//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kali/Desktop/oracel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client_step2

# Build rule for target.
client_step2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_step2
.PHONY : client_step2

# fast build rule for target.
client_step2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step2.dir/build.make CMakeFiles/client_step2.dir/build
.PHONY : client_step2/fast

#=============================================================================
# Target rules for targets named server_step2

# Build rule for target.
server_step2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_step2
.PHONY : server_step2

# fast build rule for target.
server_step2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step2.dir/build.make CMakeFiles/server_step2.dir/build
.PHONY : server_step2/fast

#=============================================================================
# Target rules for targets named client_step1

# Build rule for target.
client_step1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_step1
.PHONY : client_step1

# fast build rule for target.
client_step1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step1.dir/build.make CMakeFiles/client_step1.dir/build
.PHONY : client_step1/fast

#=============================================================================
# Target rules for targets named server_step1

# Build rule for target.
server_step1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_step1
.PHONY : server_step1

# fast build rule for target.
server_step1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step1.dir/build.make CMakeFiles/server_step1.dir/build
.PHONY : server_step1/fast

#=============================================================================
# Target rules for targets named arith_objs

# Build rule for target.
arith_objs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arith_objs
.PHONY : arith_objs

# fast build rule for target.
arith_objs/fast:
	$(MAKE) $(MAKESILENT) -f ABY/extern/ENCRYPTO_utils/extern/relic/src/CMakeFiles/arith_objs.dir/build.make ABY/extern/ENCRYPTO_utils/extern/relic/src/CMakeFiles/arith_objs.dir/build
.PHONY : arith_objs/fast

#=============================================================================
# Target rules for targets named relic_s

# Build rule for target.
relic_s: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 relic_s
.PHONY : relic_s

# fast build rule for target.
relic_s/fast:
	$(MAKE) $(MAKESILENT) -f ABY/extern/ENCRYPTO_utils/extern/relic/src/CMakeFiles/relic_s.dir/build.make ABY/extern/ENCRYPTO_utils/extern/relic/src/CMakeFiles/relic_s.dir/build
.PHONY : relic_s/fast

#=============================================================================
# Target rules for targets named encrypto_utils

# Build rule for target.
encrypto_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 encrypto_utils
.PHONY : encrypto_utils

# fast build rule for target.
encrypto_utils/fast:
	$(MAKE) $(MAKESILENT) -f ABY/extern/ENCRYPTO_utils/src/CMakeFiles/encrypto_utils.dir/build.make ABY/extern/ENCRYPTO_utils/src/CMakeFiles/encrypto_utils.dir/build
.PHONY : encrypto_utils/fast

#=============================================================================
# Target rules for targets named otextension

# Build rule for target.
otextension: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 otextension
.PHONY : otextension

# fast build rule for target.
otextension/fast:
	$(MAKE) $(MAKESILENT) -f ABY/extern/OTExtension/CMakeFiles/otextension.dir/build.make ABY/extern/OTExtension/CMakeFiles/otextension.dir/build
.PHONY : otextension/fast

#=============================================================================
# Target rules for targets named aby

# Build rule for target.
aby: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aby
.PHONY : aby

# fast build rule for target.
aby/fast:
	$(MAKE) $(MAKESILENT) -f ABY/src/abycore/CMakeFiles/aby.dir/build.make ABY/src/abycore/CMakeFiles/aby.dir/build
.PHONY : aby/fast

client_folder/client_step2_circuit.o: client_folder/client_step2_circuit.cpp.o
.PHONY : client_folder/client_step2_circuit.o

# target to build an object file
client_folder/client_step2_circuit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step2.dir/build.make CMakeFiles/client_step2.dir/client_folder/client_step2_circuit.cpp.o
.PHONY : client_folder/client_step2_circuit.cpp.o

client_folder/client_step2_circuit.i: client_folder/client_step2_circuit.cpp.i
.PHONY : client_folder/client_step2_circuit.i

# target to preprocess a source file
client_folder/client_step2_circuit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step2.dir/build.make CMakeFiles/client_step2.dir/client_folder/client_step2_circuit.cpp.i
.PHONY : client_folder/client_step2_circuit.cpp.i

client_folder/client_step2_circuit.s: client_folder/client_step2_circuit.cpp.s
.PHONY : client_folder/client_step2_circuit.s

# target to generate assembly for a file
client_folder/client_step2_circuit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step2.dir/build.make CMakeFiles/client_step2.dir/client_folder/client_step2_circuit.cpp.s
.PHONY : client_folder/client_step2_circuit.cpp.s

client_step1.o: client_step1.cpp.o
.PHONY : client_step1.o

# target to build an object file
client_step1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step1.dir/build.make CMakeFiles/client_step1.dir/client_step1.cpp.o
.PHONY : client_step1.cpp.o

client_step1.i: client_step1.cpp.i
.PHONY : client_step1.i

# target to preprocess a source file
client_step1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step1.dir/build.make CMakeFiles/client_step1.dir/client_step1.cpp.i
.PHONY : client_step1.cpp.i

client_step1.s: client_step1.cpp.s
.PHONY : client_step1.s

# target to generate assembly for a file
client_step1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step1.dir/build.make CMakeFiles/client_step1.dir/client_step1.cpp.s
.PHONY : client_step1.cpp.s

client_step2.o: client_step2.cpp.o
.PHONY : client_step2.o

# target to build an object file
client_step2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step2.dir/build.make CMakeFiles/client_step2.dir/client_step2.cpp.o
.PHONY : client_step2.cpp.o

client_step2.i: client_step2.cpp.i
.PHONY : client_step2.i

# target to preprocess a source file
client_step2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step2.dir/build.make CMakeFiles/client_step2.dir/client_step2.cpp.i
.PHONY : client_step2.cpp.i

client_step2.s: client_step2.cpp.s
.PHONY : client_step2.s

# target to generate assembly for a file
client_step2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_step2.dir/build.make CMakeFiles/client_step2.dir/client_step2.cpp.s
.PHONY : client_step2.cpp.s

server_folder/server_step2_circuit.o: server_folder/server_step2_circuit.cpp.o
.PHONY : server_folder/server_step2_circuit.o

# target to build an object file
server_folder/server_step2_circuit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step2.dir/build.make CMakeFiles/server_step2.dir/server_folder/server_step2_circuit.cpp.o
.PHONY : server_folder/server_step2_circuit.cpp.o

server_folder/server_step2_circuit.i: server_folder/server_step2_circuit.cpp.i
.PHONY : server_folder/server_step2_circuit.i

# target to preprocess a source file
server_folder/server_step2_circuit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step2.dir/build.make CMakeFiles/server_step2.dir/server_folder/server_step2_circuit.cpp.i
.PHONY : server_folder/server_step2_circuit.cpp.i

server_folder/server_step2_circuit.s: server_folder/server_step2_circuit.cpp.s
.PHONY : server_folder/server_step2_circuit.s

# target to generate assembly for a file
server_folder/server_step2_circuit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step2.dir/build.make CMakeFiles/server_step2.dir/server_folder/server_step2_circuit.cpp.s
.PHONY : server_folder/server_step2_circuit.cpp.s

server_step1.o: server_step1.cpp.o
.PHONY : server_step1.o

# target to build an object file
server_step1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step1.dir/build.make CMakeFiles/server_step1.dir/server_step1.cpp.o
.PHONY : server_step1.cpp.o

server_step1.i: server_step1.cpp.i
.PHONY : server_step1.i

# target to preprocess a source file
server_step1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step1.dir/build.make CMakeFiles/server_step1.dir/server_step1.cpp.i
.PHONY : server_step1.cpp.i

server_step1.s: server_step1.cpp.s
.PHONY : server_step1.s

# target to generate assembly for a file
server_step1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step1.dir/build.make CMakeFiles/server_step1.dir/server_step1.cpp.s
.PHONY : server_step1.cpp.s

server_step2.o: server_step2.cpp.o
.PHONY : server_step2.o

# target to build an object file
server_step2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step2.dir/build.make CMakeFiles/server_step2.dir/server_step2.cpp.o
.PHONY : server_step2.cpp.o

server_step2.i: server_step2.cpp.i
.PHONY : server_step2.i

# target to preprocess a source file
server_step2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step2.dir/build.make CMakeFiles/server_step2.dir/server_step2.cpp.i
.PHONY : server_step2.cpp.i

server_step2.s: server_step2.cpp.s
.PHONY : server_step2.s

# target to generate assembly for a file
server_step2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_step2.dir/build.make CMakeFiles/server_step2.dir/server_step2.cpp.s
.PHONY : server_step2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... arith_objs"
	@echo "... aby"
	@echo "... client_step1"
	@echo "... client_step2"
	@echo "... encrypto_utils"
	@echo "... otextension"
	@echo "... relic_s"
	@echo "... server_step1"
	@echo "... server_step2"
	@echo "... client_folder/client_step2_circuit.o"
	@echo "... client_folder/client_step2_circuit.i"
	@echo "... client_folder/client_step2_circuit.s"
	@echo "... client_step1.o"
	@echo "... client_step1.i"
	@echo "... client_step1.s"
	@echo "... client_step2.o"
	@echo "... client_step2.i"
	@echo "... client_step2.s"
	@echo "... server_folder/server_step2_circuit.o"
	@echo "... server_folder/server_step2_circuit.i"
	@echo "... server_folder/server_step2_circuit.s"
	@echo "... server_step1.o"
	@echo "... server_step1.i"
	@echo "... server_step1.s"
	@echo "... server_step2.o"
	@echo "... server_step2.i"
	@echo "... server_step2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

